//
// Copyright 2021 The Feast Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: protos/feast/core/RequestFeatureView.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestFeatureView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User-specified specifications of this feature view.
	Spec *RequestFeatureViewSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *RequestFeatureView) Reset() {
	*x = RequestFeatureView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_core_RequestFeatureView_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFeatureView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFeatureView) ProtoMessage() {}

func (x *RequestFeatureView) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_core_RequestFeatureView_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFeatureView.ProtoReflect.Descriptor instead.
func (*RequestFeatureView) Descriptor() ([]byte, []int) {
	return file_protos_feast_core_RequestFeatureView_proto_rawDescGZIP(), []int{0}
}

func (x *RequestFeatureView) GetSpec() *RequestFeatureViewSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Next available id: 7
type RequestFeatureViewSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the feature view. Must be unique. Not updated.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Name of Feast project that this feature view belongs to.
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// Request data which contains the underlying data schema and list of associated features
	RequestDataSource *DataSource `protobuf:"bytes,3,opt,name=request_data_source,json=requestDataSource,proto3" json:"request_data_source,omitempty"`
	// Description of the request feature view.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// User defined metadata.
	Tags map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Owner of the request feature view.
	Owner string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *RequestFeatureViewSpec) Reset() {
	*x = RequestFeatureViewSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_core_RequestFeatureView_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFeatureViewSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFeatureViewSpec) ProtoMessage() {}

func (x *RequestFeatureViewSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_core_RequestFeatureView_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFeatureViewSpec.ProtoReflect.Descriptor instead.
func (*RequestFeatureViewSpec) Descriptor() ([]byte, []int) {
	return file_protos_feast_core_RequestFeatureView_proto_rawDescGZIP(), []int{1}
}

func (x *RequestFeatureViewSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestFeatureViewSpec) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RequestFeatureViewSpec) GetRequestDataSource() *DataSource {
	if x != nil {
		return x.RequestDataSource
	}
	return nil
}

func (x *RequestFeatureViewSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestFeatureViewSpec) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RequestFeatureViewSpec) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

var File_protos_feast_core_RequestFeatureView_proto protoreflect.FileDescriptor

var file_protos_feast_core_RequestFeatureView_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x66, 0x65,
	0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x12,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x69,
	0x65, 0x77, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0xc1, 0x02, 0x0a, 0x16, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x69, 0x65,
	0x77, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x46, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x66, 0x65,
	0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x69, 0x65, 0x77, 0x53, 0x70, 0x65, 0x63, 0x2e,
	0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x1a, 0x37, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x37,
	0x0a, 0x10, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x42, 0x17, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x0a, 0x66, 0x65, 0x61,
	0x73, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_feast_core_RequestFeatureView_proto_rawDescOnce sync.Once
	file_protos_feast_core_RequestFeatureView_proto_rawDescData = file_protos_feast_core_RequestFeatureView_proto_rawDesc
)

func file_protos_feast_core_RequestFeatureView_proto_rawDescGZIP() []byte {
	file_protos_feast_core_RequestFeatureView_proto_rawDescOnce.Do(func() {
		file_protos_feast_core_RequestFeatureView_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_feast_core_RequestFeatureView_proto_rawDescData)
	})
	return file_protos_feast_core_RequestFeatureView_proto_rawDescData
}

var file_protos_feast_core_RequestFeatureView_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_feast_core_RequestFeatureView_proto_goTypes = []interface{}{
	(*RequestFeatureView)(nil),     // 0: feast.core.RequestFeatureView
	(*RequestFeatureViewSpec)(nil), // 1: feast.core.RequestFeatureViewSpec
	nil,                            // 2: feast.core.RequestFeatureViewSpec.TagsEntry
	(*DataSource)(nil),             // 3: feast.core.DataSource
}
var file_protos_feast_core_RequestFeatureView_proto_depIdxs = []int32{
	1, // 0: feast.core.RequestFeatureView.spec:type_name -> feast.core.RequestFeatureViewSpec
	3, // 1: feast.core.RequestFeatureViewSpec.request_data_source:type_name -> feast.core.DataSource
	2, // 2: feast.core.RequestFeatureViewSpec.tags:type_name -> feast.core.RequestFeatureViewSpec.TagsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_feast_core_RequestFeatureView_proto_init() }
func file_protos_feast_core_RequestFeatureView_proto_init() {
	if File_protos_feast_core_RequestFeatureView_proto != nil {
		return
	}
	file_protos_feast_core_DataSource_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_feast_core_RequestFeatureView_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFeatureView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_feast_core_RequestFeatureView_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFeatureViewSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_feast_core_RequestFeatureView_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_feast_core_RequestFeatureView_proto_goTypes,
		DependencyIndexes: file_protos_feast_core_RequestFeatureView_proto_depIdxs,
		MessageInfos:      file_protos_feast_core_RequestFeatureView_proto_msgTypes,
	}.Build()
	File_protos_feast_core_RequestFeatureView_proto = out.File
	file_protos_feast_core_RequestFeatureView_proto_rawDesc = nil
	file_protos_feast_core_RequestFeatureView_proto_goTypes = nil
	file_protos_feast_core_RequestFeatureView_proto_depIdxs = nil
}
