//
// Copyright 2021 The Feast Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: protos/feast/core/ValidationProfile.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GEValidationProfiler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiler *GEValidationProfiler_UserDefinedProfiler `protobuf:"bytes,1,opt,name=profiler,proto3" json:"profiler,omitempty"`
}

func (x *GEValidationProfiler) Reset() {
	*x = GEValidationProfiler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GEValidationProfiler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEValidationProfiler) ProtoMessage() {}

func (x *GEValidationProfiler) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEValidationProfiler.ProtoReflect.Descriptor instead.
func (*GEValidationProfiler) Descriptor() ([]byte, []int) {
	return file_protos_feast_core_ValidationProfile_proto_rawDescGZIP(), []int{0}
}

func (x *GEValidationProfiler) GetProfiler() *GEValidationProfiler_UserDefinedProfiler {
	if x != nil {
		return x.Profiler
	}
	return nil
}

type GEValidationProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// JSON-serialized ExpectationSuite object
	ExpectationSuite []byte `protobuf:"bytes,1,opt,name=expectation_suite,json=expectationSuite,proto3" json:"expectation_suite,omitempty"`
}

func (x *GEValidationProfile) Reset() {
	*x = GEValidationProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GEValidationProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEValidationProfile) ProtoMessage() {}

func (x *GEValidationProfile) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEValidationProfile.ProtoReflect.Descriptor instead.
func (*GEValidationProfile) Descriptor() ([]byte, []int) {
	return file_protos_feast_core_ValidationProfile_proto_rawDescGZIP(), []int{1}
}

func (x *GEValidationProfile) GetExpectationSuite() []byte {
	if x != nil {
		return x.ExpectationSuite
	}
	return nil
}

type ValidationReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique name of validation reference within the project
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Name of saved dataset used as reference dataset
	ReferenceDatasetName string `protobuf:"bytes,2,opt,name=reference_dataset_name,json=referenceDatasetName,proto3" json:"reference_dataset_name,omitempty"`
	// Name of Feast project that this object source belongs to
	Project string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// Description of the validation reference
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// User defined metadata
	Tags map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// validation profiler
	//
	// Types that are assignable to Profiler:
	//	*ValidationReference_GeProfiler
	Profiler isValidationReference_Profiler `protobuf_oneof:"profiler"`
	// (optional) cached validation profile (to avoid constant recalculation)
	//
	// Types that are assignable to CachedProfile:
	//	*ValidationReference_GeProfile
	CachedProfile isValidationReference_CachedProfile `protobuf_oneof:"cached_profile"`
}

func (x *ValidationReference) Reset() {
	*x = ValidationReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationReference) ProtoMessage() {}

func (x *ValidationReference) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationReference.ProtoReflect.Descriptor instead.
func (*ValidationReference) Descriptor() ([]byte, []int) {
	return file_protos_feast_core_ValidationProfile_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidationReference) GetReferenceDatasetName() string {
	if x != nil {
		return x.ReferenceDatasetName
	}
	return ""
}

func (x *ValidationReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ValidationReference) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ValidationReference) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (m *ValidationReference) GetProfiler() isValidationReference_Profiler {
	if m != nil {
		return m.Profiler
	}
	return nil
}

func (x *ValidationReference) GetGeProfiler() *GEValidationProfiler {
	if x, ok := x.GetProfiler().(*ValidationReference_GeProfiler); ok {
		return x.GeProfiler
	}
	return nil
}

func (m *ValidationReference) GetCachedProfile() isValidationReference_CachedProfile {
	if m != nil {
		return m.CachedProfile
	}
	return nil
}

func (x *ValidationReference) GetGeProfile() *GEValidationProfile {
	if x, ok := x.GetCachedProfile().(*ValidationReference_GeProfile); ok {
		return x.GeProfile
	}
	return nil
}

type isValidationReference_Profiler interface {
	isValidationReference_Profiler()
}

type ValidationReference_GeProfiler struct {
	GeProfiler *GEValidationProfiler `protobuf:"bytes,6,opt,name=ge_profiler,json=geProfiler,proto3,oneof"`
}

func (*ValidationReference_GeProfiler) isValidationReference_Profiler() {}

type isValidationReference_CachedProfile interface {
	isValidationReference_CachedProfile()
}

type ValidationReference_GeProfile struct {
	GeProfile *GEValidationProfile `protobuf:"bytes,7,opt,name=ge_profile,json=geProfile,proto3,oneof"`
}

func (*ValidationReference_GeProfile) isValidationReference_CachedProfile() {}

type GEValidationProfiler_UserDefinedProfiler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The python-syntax function body (serialized by dill)
	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GEValidationProfiler_UserDefinedProfiler) Reset() {
	*x = GEValidationProfiler_UserDefinedProfiler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GEValidationProfiler_UserDefinedProfiler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEValidationProfiler_UserDefinedProfiler) ProtoMessage() {}

func (x *GEValidationProfiler_UserDefinedProfiler) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_core_ValidationProfile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEValidationProfiler_UserDefinedProfiler.ProtoReflect.Descriptor instead.
func (*GEValidationProfiler_UserDefinedProfiler) Descriptor() ([]byte, []int) {
	return file_protos_feast_core_ValidationProfile_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GEValidationProfiler_UserDefinedProfiler) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_protos_feast_core_ValidationProfile_proto protoreflect.FileDescriptor

var file_protos_feast_core_ValidationProfile_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x66, 0x65, 0x61,
	0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x47, 0x45, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72,
	0x12, 0x50, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x34, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x47, 0x45, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x72, 0x1a, 0x29, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x42, 0x0a,
	0x13, 0x47, 0x45, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x10, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x69, 0x74,
	0x65, 0x22, 0xb8, 0x03, 0x0a, 0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a,
	0x16, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3d, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x54,
	0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x43,
	0x0a, 0x0b, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x47, 0x45, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0a, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x45, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x01, 0x52, 0x09, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x37, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x10, 0x0a, 0x0e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x31, 0x0a, 0x10,
	0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x42, 0x11, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x5a, 0x0a, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_feast_core_ValidationProfile_proto_rawDescOnce sync.Once
	file_protos_feast_core_ValidationProfile_proto_rawDescData = file_protos_feast_core_ValidationProfile_proto_rawDesc
)

func file_protos_feast_core_ValidationProfile_proto_rawDescGZIP() []byte {
	file_protos_feast_core_ValidationProfile_proto_rawDescOnce.Do(func() {
		file_protos_feast_core_ValidationProfile_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_feast_core_ValidationProfile_proto_rawDescData)
	})
	return file_protos_feast_core_ValidationProfile_proto_rawDescData
}

var file_protos_feast_core_ValidationProfile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_feast_core_ValidationProfile_proto_goTypes = []interface{}{
	(*GEValidationProfiler)(nil),                     // 0: feast.core.GEValidationProfiler
	(*GEValidationProfile)(nil),                      // 1: feast.core.GEValidationProfile
	(*ValidationReference)(nil),                      // 2: feast.core.ValidationReference
	(*GEValidationProfiler_UserDefinedProfiler)(nil), // 3: feast.core.GEValidationProfiler.UserDefinedProfiler
	nil, // 4: feast.core.ValidationReference.TagsEntry
}
var file_protos_feast_core_ValidationProfile_proto_depIdxs = []int32{
	3, // 0: feast.core.GEValidationProfiler.profiler:type_name -> feast.core.GEValidationProfiler.UserDefinedProfiler
	4, // 1: feast.core.ValidationReference.tags:type_name -> feast.core.ValidationReference.TagsEntry
	0, // 2: feast.core.ValidationReference.ge_profiler:type_name -> feast.core.GEValidationProfiler
	1, // 3: feast.core.ValidationReference.ge_profile:type_name -> feast.core.GEValidationProfile
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_feast_core_ValidationProfile_proto_init() }
func file_protos_feast_core_ValidationProfile_proto_init() {
	if File_protos_feast_core_ValidationProfile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_feast_core_ValidationProfile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GEValidationProfiler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_feast_core_ValidationProfile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GEValidationProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_feast_core_ValidationProfile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_feast_core_ValidationProfile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GEValidationProfiler_UserDefinedProfiler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_feast_core_ValidationProfile_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ValidationReference_GeProfiler)(nil),
		(*ValidationReference_GeProfile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_feast_core_ValidationProfile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_feast_core_ValidationProfile_proto_goTypes,
		DependencyIndexes: file_protos_feast_core_ValidationProfile_proto_depIdxs,
		MessageInfos:      file_protos_feast_core_ValidationProfile_proto_msgTypes,
	}.Build()
	File_protos_feast_core_ValidationProfile_proto = out.File
	file_protos_feast_core_ValidationProfile_proto_rawDesc = nil
	file_protos_feast_core_ValidationProfile_proto_goTypes = nil
	file_protos_feast_core_ValidationProfile_proto_depIdxs = nil
}
