// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: protos/feast/serving/Connector.proto

package serving

import (
	types "github.com/Golang-Tools/feasthelper/feast/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectorFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference *FeatureReferenceV2    `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value     *types.Value           `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConnectorFeature) Reset() {
	*x = ConnectorFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_serving_Connector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectorFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorFeature) ProtoMessage() {}

func (x *ConnectorFeature) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_serving_Connector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorFeature.ProtoReflect.Descriptor instead.
func (*ConnectorFeature) Descriptor() ([]byte, []int) {
	return file_protos_feast_serving_Connector_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorFeature) GetReference() *FeatureReferenceV2 {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *ConnectorFeature) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ConnectorFeature) GetValue() *types.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type ConnectorFeatureList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeatureList []*ConnectorFeature `protobuf:"bytes,1,rep,name=featureList,proto3" json:"featureList,omitempty"`
}

func (x *ConnectorFeatureList) Reset() {
	*x = ConnectorFeatureList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_serving_Connector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectorFeatureList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorFeatureList) ProtoMessage() {}

func (x *ConnectorFeatureList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_serving_Connector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorFeatureList.ProtoReflect.Descriptor instead.
func (*ConnectorFeatureList) Descriptor() ([]byte, []int) {
	return file_protos_feast_serving_Connector_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectorFeatureList) GetFeatureList() []*ConnectorFeature {
	if x != nil {
		return x.FeatureList
	}
	return nil
}

type OnlineReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityKeys []*types.EntityKey `protobuf:"bytes,1,rep,name=entityKeys,proto3" json:"entityKeys,omitempty"`
	View       string             `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	Features   []string           `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
}

func (x *OnlineReadRequest) Reset() {
	*x = OnlineReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_serving_Connector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReadRequest) ProtoMessage() {}

func (x *OnlineReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_serving_Connector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReadRequest.ProtoReflect.Descriptor instead.
func (*OnlineReadRequest) Descriptor() ([]byte, []int) {
	return file_protos_feast_serving_Connector_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineReadRequest) GetEntityKeys() []*types.EntityKey {
	if x != nil {
		return x.EntityKeys
	}
	return nil
}

func (x *OnlineReadRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *OnlineReadRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type OnlineReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ConnectorFeatureList `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *OnlineReadResponse) Reset() {
	*x = OnlineReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_feast_serving_Connector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReadResponse) ProtoMessage() {}

func (x *OnlineReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_feast_serving_Connector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReadResponse.ProtoReflect.Descriptor instead.
func (*OnlineReadResponse) Descriptor() ([]byte, []int) {
	return file_protos_feast_serving_Connector_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineReadResponse) GetResults() []*ConnectorFeatureList {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_protos_feast_serving_Connector_proto protoreflect.FileDescriptor

var file_protos_feast_serving_Connector_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x29, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e,
	0x67, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2e, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x56,
	0x32, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x5a, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x0b, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x7b, 0x0a, 0x11,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x36, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65,
	0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x12, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3e, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32,
	0x62, 0x0a, 0x0b, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x53,
	0x0a, 0x0a, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x61, 0x64, 0x12, 0x21, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_feast_serving_Connector_proto_rawDescOnce sync.Once
	file_protos_feast_serving_Connector_proto_rawDescData = file_protos_feast_serving_Connector_proto_rawDesc
)

func file_protos_feast_serving_Connector_proto_rawDescGZIP() []byte {
	file_protos_feast_serving_Connector_proto_rawDescOnce.Do(func() {
		file_protos_feast_serving_Connector_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_feast_serving_Connector_proto_rawDescData)
	})
	return file_protos_feast_serving_Connector_proto_rawDescData
}

var file_protos_feast_serving_Connector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_feast_serving_Connector_proto_goTypes = []interface{}{
	(*ConnectorFeature)(nil),      // 0: grpc.connector.ConnectorFeature
	(*ConnectorFeatureList)(nil),  // 1: grpc.connector.ConnectorFeatureList
	(*OnlineReadRequest)(nil),     // 2: grpc.connector.OnlineReadRequest
	(*OnlineReadResponse)(nil),    // 3: grpc.connector.OnlineReadResponse
	(*FeatureReferenceV2)(nil),    // 4: feast.serving.FeatureReferenceV2
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*types.Value)(nil),           // 6: feast.types.Value
	(*types.EntityKey)(nil),       // 7: feast.types.EntityKey
}
var file_protos_feast_serving_Connector_proto_depIdxs = []int32{
	4, // 0: grpc.connector.ConnectorFeature.reference:type_name -> feast.serving.FeatureReferenceV2
	5, // 1: grpc.connector.ConnectorFeature.timestamp:type_name -> google.protobuf.Timestamp
	6, // 2: grpc.connector.ConnectorFeature.value:type_name -> feast.types.Value
	0, // 3: grpc.connector.ConnectorFeatureList.featureList:type_name -> grpc.connector.ConnectorFeature
	7, // 4: grpc.connector.OnlineReadRequest.entityKeys:type_name -> feast.types.EntityKey
	1, // 5: grpc.connector.OnlineReadResponse.results:type_name -> grpc.connector.ConnectorFeatureList
	2, // 6: grpc.connector.OnlineStore.OnlineRead:input_type -> grpc.connector.OnlineReadRequest
	3, // 7: grpc.connector.OnlineStore.OnlineRead:output_type -> grpc.connector.OnlineReadResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_feast_serving_Connector_proto_init() }
func file_protos_feast_serving_Connector_proto_init() {
	if File_protos_feast_serving_Connector_proto != nil {
		return
	}
	file_protos_feast_serving_ServingService_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_feast_serving_Connector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectorFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_feast_serving_Connector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectorFeatureList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_feast_serving_Connector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_feast_serving_Connector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_feast_serving_Connector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_feast_serving_Connector_proto_goTypes,
		DependencyIndexes: file_protos_feast_serving_Connector_proto_depIdxs,
		MessageInfos:      file_protos_feast_serving_Connector_proto_msgTypes,
	}.Build()
	File_protos_feast_serving_Connector_proto = out.File
	file_protos_feast_serving_Connector_proto_rawDesc = nil
	file_protos_feast_serving_Connector_proto_goTypes = nil
	file_protos_feast_serving_Connector_proto_depIdxs = nil
}
